<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Welcome to Amazon Customer Service</name>
   <tag></tag>
   <elementGuidId>b9125e95-1342-4517-92eb-18978f3033cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.fs-heading.bolded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hub-gateway-app-unauth']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f8a2dedb-fea8-490f-b377-782a71e9a4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-heading bolded</value>
      <webElementGuid>d17ec5c3-45d5-4b9a-835f-a54afd084664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to Amazon Customer Service</value>
      <webElementGuid>3e4155d8-f01e-446e-9c24-b0f1a6a9d67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hub-gateway-app-unauth&quot;)/div[@class=&quot;page-wrapper hero-banner&quot;]/div[@class=&quot;page-container&quot;]/h1[@class=&quot;fs-heading bolded&quot;]</value>
      <webElementGuid>b217cb17-5d33-4475-aee6-bb92bc480b4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hub-gateway-app-unauth']/div/div/h1</value>
      <webElementGuid>30679607-7336-421f-9a1e-15976591bf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>c6a116e1-3258-4c7d-b2ff-902c8ce38d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Welcome to Amazon Customer Service' or . = 'Welcome to Amazon Customer Service')]</value>
      <webElementGuid>6fe1f624-2c74-4b0e-93b1-bfa786bf14c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
