<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>3cce8d68-d194-4a39-bf22-dd3ad6e9ec8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-3-announce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='a-autoid-3-announce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e87ef956-94a6-4ba6-a69a-2bde334ccc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>glowDoneButton</value>
      <webElementGuid>3712a979-7f09-4480-90e8-10f556fe5938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>42b5d8ac-9ee9-4735-b070-666d5da3443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>692f2363-c369-4ad8-81f1-25b122fac3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-3-announce</value>
      <webElementGuid>283c6a06-942d-4193-bff1-2d37cd7ea596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>515a94c8-e16d-40c1-bb66-fe9d38398858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-3-announce&quot;)</value>
      <webElementGuid>780080fd-307d-42d0-a560-d6efc90c88b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='a-autoid-3-announce']</value>
      <webElementGuid>b4066d38-a1b0-4256-83b5-e2fe82958d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-3']/span/button</value>
      <webElementGuid>06be5c47-5103-4a04-a7b3-158b03fb219d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>894c214e-6362-46ad-a731-a9e733ac809f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'glowDoneButton' and @type = 'button' and @id = 'a-autoid-3-announce' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>d55ea41c-c347-4065-8088-19f002b75645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='a-autoid-1-announce']</value>
      <webElementGuid>0db4b9c0-4b3d-4fc7-8de8-0baa76550a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-1']/span/button</value>
      <webElementGuid>0545f82a-b74f-478c-9036-d5b6ee990142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'glowDoneButton' and @type = 'button' and @id = 'a-autoid-1-announce' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>23542b40-88ed-46fa-aa9a-9dce2e65e59f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
