<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Choose your location</name>
   <tag></tag>
   <elementGuidId>442d509a-1047-4b39-a7be-3330ab3a80a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-popover-header-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='a-popover-header-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5d81fde9-9620-4f4f-876a-ae32e3f28a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-popover-header-content</value>
      <webElementGuid>f0774096-2600-471b-82c5-1dd676d40d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-popover-header-1</value>
      <webElementGuid>a72acfae-22a9-4373-ad10-85f4c2f26132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose your location</value>
      <webElementGuid>c9ae9f5d-5597-4bc9-becf-fdb27504bb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-header-1&quot;)</value>
      <webElementGuid>d95c16a4-8049-4c01-a5a2-7bce3a53c57e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='a-popover-header-1']</value>
      <webElementGuid>e8ae9677-b281-4be7-bd24-92873ab53f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/header/h4</value>
      <webElementGuid>72fb1e16-9f37-4432-9453-f7a36906b0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>9b9e2617-f5b8-44f0-842a-45916c126bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'a-popover-header-1' and (text() = 'Choose your location' or . = 'Choose your location')]</value>
      <webElementGuid>bcf87273-7af0-4238-87ab-87192f740af2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
